apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: iot_data
    user: admin
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    isDefault: true

  - name: MQTT
    type: mqtt
    jsonData:
      url: ws://mqtt:9001   # Using internal Docker network
      topic: users/+/devices/+/sensor/+
      qos: 0
      processMessageAsJson: true